UI components
newfold-labs/js-utility-ai pull request #2
Opened 2023-06-21 10:41 UTC by ajayadav09

Added a React UI Component for generating site description.

2023-06-21 11:09 UTC, aulisius requested changes

2023-06-21 11:09 UTC, aulisius commented on dist/index.js.LICENSE.txt
This can be added to .gitignore

2023-06-21 11:09 UTC, aulisius commented on webpack.config.js
We should look into `wp-scripts` instead of writing custom webpack configurations

2023-06-21 11:09 UTC, aulisius commented on yarn.lock
Do we need both lockfiles? Let's stick with `package-lock.json`

2023-06-21 14:54 UTC, ajayadav09 commented on webpack.config.js
Thank you. Will check how to use wp-scripts instead of webpack config

2023-08-11 15:18 UTC, ajayadav09 commented on webpack.config.js
Added wp-scripts

2025-01-28 14:01 UTC, closed without merging

2025-01-28 14:01 UTC, ajayadav09 commented
Closing this PR as it's outdated